version: '3.8'

services:
  app:
    build: .
    container_name: faqs-app
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - [${PATH TOGOOGLE_TRANSLATE_KEY}]:/usr/src/app/keys
    env_file:
      - .env
    environment:
      NODE_ENV: development
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: